AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template that creates a Lambda backed Custom Resource

Parameters:
  BucketName:
    Type: String
    Description: Enter name of S3 bucket where Lambda jar file is uploaded.
  Input:
    Type: String
    Description: Enter input string
    Default: 'QWERTYuiop'

Mappings:
  Constants:
    InstanceValues:
      ArtifactName: custom-resource.zip
      LogRetentionPeriod: 7

Resources:
  LambdaExecutionPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: Policy for executing lambda function
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Resource: 'arn:aws:s3:::*'
          - Effect: Allow
            Action:
              - 'logs:*'
            Resource: 'arn:aws:logs:*:*:*'

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Ref LambdaExecutionPolicy

  CustomResourceLambda:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: index.handler
      Code:
        S3Bucket: !Ref BucketName
        S3Key: !FindInMap 
          - Constants
          - InstanceValues
          - ArtifactName
      Environment:
        Variables:
          env: dev
      Runtime: python2.7
      Timeout: 60

  CustomResourceLambdaLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CustomResourceLambda}"
      RetentionInDays: !FindInMap [Constants, InstanceValues, LogRetentionPeriod]

  CustomResource:
    Type: AWS::CloudFormation::CustomResource
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt 
        - CustomResourceLambda
        - Arn
      Input: !Ref Input

Outputs: 
  CustomResourceValue: 
    Value: 
      Fn::GetAtt: 
        - CustomResource
        - Output