AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple Lambda function saying "Hello World".
Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.sample.aws.aws_sam.function.HelloWorld
      Runtime: java8
      CodeUri: ./